version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/mongodb
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
  todo-back-dev:
    image: todo-back-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment:
      MONGO_URL: mongodb://dev_username:dev_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
