### READ all Blogs
GET http://localhost:3001/api/blogs

### READ one Blog
GET http://localhost:3001/api/blogs/1

### CREATE Blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWtAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2MjY2MTMzNn0.75x65v1m5hwgVqrYJ0SpG0cAkhnQMSPkcsEFM2TXsro

{
  "author": "Joe Johnson",
  "title": "Top 11 people",
  "url": "https://www.economist.com/",
  "likes": "193",
  "year": 1998
}

### UPDATE Blog
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": "197"
}

### DELETE Blog
DELETE http://localhost:3001/api/blogs/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWsiLCJpZCI6MSwiaWF0IjoxNjYyMjAzMTI5fQ.I47eq33aezwM_7ld_fa2b4kLJfOBTPtg8nEGrh-iX5U


### READ all Users
GET http://localhost:3001/api/users

### READ one User
GET http://localhost:3001/api/users/1

### CREATE User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "erik@gmail.com",
  "name": "Erik Erikson"
}

### UPDATE User
PUT http://localhost:3001/api/users/erikson
Content-Type: application/json

{
  "username": "erik"
}

### LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "erik@gmail.com",
  "password": "secret"
}

### CREATE Reading
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": 1,
  "userId": 1
}
