### READ all Blogs
GET http://localhost:3001/api/blogs

### READ one Blog
GET http://localhost:3001/api/blogs/1

### CREATE Blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWtAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY2MjY1ODU5Mn0.afQ9-vn4i0_dvI505mK_gqfIDQUU5t4wL_IIrn1rXLE

{
  "author": "Joe Johnson",
  "title": "Top 10 people",
  "url": "https://www.economist.com/",
  "likes": "193"
}

### UPDATE Blog
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": "197"
}

### DELETE Blog
DELETE http://localhost:3001/api/blogs/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWsiLCJpZCI6MSwiaWF0IjoxNjYyMjAzMTI5fQ.I47eq33aezwM_7ld_fa2b4kLJfOBTPtg8nEGrh-iX5U


### READ all Users
GET http://localhost:3001/api/users

### READ one User
GET http://localhost:3001/api/users/1

### CREATE User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "erik@gmail.com",
  "name": "Erik Erikson"
}

### UPDATE User
PUT http://localhost:3001/api/users/erikson
Content-Type: application/json

{
  "username": "erik"
}

### LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "erik@gmail.com",
  "password": "secret"
}
