version: '3.8'

services:
  app:
    image: todo-front
    container_name: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./todo-frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/mongodb
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-back
    container_name: todo-back
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      MONGO_URL: mongodb://db_user:db_pwd@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
  busybox:
    image: busybox
