###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Top 10 people",
  "author": "Joe Johnson",
  "url": "https://www.economist.com/",
  "likes": "193"
}

###
DELETE http://localhost:3003/api/blogs/622cd56f5a39ca8c235eecce

###
PUT http://localhost:3003/api/blogs/622cb479640263f2f0f11906
Content-Type: application/json

{
  "title": "Top 10 people",
  "author": "Joe Johnson",
  "url": "https://www.economist.com/",
  "likes": "194"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mary",
  "name": "Mary Poppins",
  "password": "secretword10101"
}