version: '3.8'

services:
  app:
    image: todo-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: todo-front
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
